# rules common to all c++ projects
# set vars: TARGET, VER, MSRC

CC               = $(CXX)

SRC              = $(wildcard *.cc)

OBJ              = $(SRC:.cc=.o) $(MSRC:%.h=.moc.%.o)

$(TARGET): $(OBJ)

clean:
	rm -f *.o .*.o *.rpo

clobber: clean 
	rm -f $(TARGET) core *~ *# .dep.* .moc.* 

BASEDIR = /tmp/dist
DISTNAME = $(TARGET)-$(VER)
DISTFULL = $(DISTNAME).tar.gz
LSMFULL = $(DISTNAME).lsm
AUTHOR = "suntong001@users.sourceforge.net (Tong Sun)"
WEBPAGE = http://savannah.nongnu.org/projects/qdiff

dist: clobber
	@mkdir -p $(BASEDIR)
	@rm -rf $(BASEDIR)/$(DISTNAME)*
	@mkdir $(BASEDIR)/$(DISTNAME)
	@cp -r * $(BASEDIR)/$(DISTNAME)
	@rm -rf $(BASEDIR)/$(DISTNAME)/NODIST
	@find $(BASEDIR)/$(DISTNAME) -name '*.h' -or -name '*.cc' -or -name '*.c'|xargs -n1 check_for_gpl_header
	@mv $(BASEDIR)/$(DISTNAME)/LSM_ENTRY $(BASEDIR)/$(LSMFULL)
	@tar -C $(BASEDIR) -czf $(BASEDIR)/$(DISTFULL) $(DISTNAME)
	@rm -rf $(BASEDIR)/$(DISTNAME)
	@streplace -q __VERSION__=$(VER) $(BASEDIR)/$(LSMFULL)
	@streplace -q __AUTHOR__=$(AUTHOR) $(BASEDIR)/$(LSMFULL)
	@streplace -q __WEBPAGE__=$(WEBPAGE) $(BASEDIR)/$(LSMFULL)
	@streplace -q __TITLE__=$(TARGET) $(BASEDIR)/$(LSMFULL)
	@streplace -q "__DATE__=`date -R`" $(BASEDIR)/$(LSMFULL)
	@streplace -q "__LSM_NAME__=`ls $(BASEDIR)/$(LSMFULL) -l -s |awk '{printf "%3sk %s\n",$$1,substr($$10,11)}'`" $(BASEDIR)/$(LSMFULL)
	@streplace -q "__TAR_NAME__=`ls $(BASEDIR)/$(DISTFULL) -l -s |awk '{printf "%3sk %s\n",$$1,substr($$10,11)}'`" $(BASEDIR)/$(LSMFULL)
	@streplace -q __MD5SUM__=`md5sum $(BASEDIR)/$(DISTFULL)|awk '{print $$1}'` $(BASEDIR)/$(LSMFULL)
	@echo
	@echo "==> lsm-file             is at $(BASEDIR)/$(LSMFULL)"
	@echo "==> distribution package is at $(BASEDIR)/$(DISTFULL)"

# meta object compiler for qt
.moc.%.cc: %.h
	$(MOC) -o $@ $<

# dependencies
.dep.%: %.cc
	@$(SHELL) -ec '$(CXX) $(CPPFLAGS) -MM $< | sed '\''s/$*\.o/& $@/g'\'' > $@'

-include $(OBJ:%.o=.dep.%)

